package rpc

type RPC_TYPE = uint

const (
	RPC_TYPE_APPEND_ENTRIES_REQ RPC_TYPE = iota
	RPC_TYPE_APPEND_ENTRIES_RES
	RPC_TYPE_REQUEST_VOTE_REQ
	RPC_TYPE_REQUEST_VOTE_RES
	RPC_TYPE_STATE_ACTION_REQ
)
